"""empty message

Revision ID: b25a779e6318
Revises: 
Create Date: 2024-11-25 16:10:44.773968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25a779e6318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('set_temperature', sa.Float(), nullable=False),
    sa.Column('set_humidity', sa.Float(), nullable=False),
    sa.Column('set_solidHumidity', sa.Float(), nullable=False),
    sa.Column('set_illuminance', sa.Float(), nullable=False),
    sa.Column('set_co2Concentration', sa.Float(), nullable=False),
    sa.Column('set_waterTemperature', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('solidHumidity', sa.Float(), nullable=False),
    sa.Column('illuminance', sa.Float(), nullable=False),
    sa.Column('co2Concentration', sa.Float(), nullable=False),
    sa.Column('waterTemperature', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_status')
    op.drop_table('crops')
    # ### end Alembic commands ###
