"""empty message

Revision ID: e9f6f2d0eace
Revises: 2d0eb1a212d8
Create Date: 2024-10-30 13:21:21.415225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f6f2d0eace'
down_revision: Union[str, None] = '2d0eb1a212d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('solidHumidity', sa.Float(), nullable=False),
    sa.Column('illuminance', sa.Float(), nullable=False),
    sa.Column('co2Concentration', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('environmentStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmentStatus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('humidity', sa.FLOAT(), nullable=False),
    sa.Column('solidHumidity', sa.FLOAT(), nullable=False),
    sa.Column('illuminance', sa.FLOAT(), nullable=False),
    sa.Column('co2Concentration', sa.FLOAT(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('crop_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('environment_status')
    # ### end Alembic commands ###
